trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
    node --version
    npm install -g npm@latest
    npm install @salesforce/cli --global

