trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      sudo apt-get install libssl-dev
      ls
      openssl version

#- task: UseNode@1
#  inputs:
#    checkLatest: true

- script:  |
   cd /home/vsts/work/1/s
   ls
   cd /home/vsts/work
   ls
   cd /home/vsts/work
   ls
   cd /usr/bin/openssl
   ls
   cd /usr/bin
   ls
   cd /usr/local
   ls
   echo 'OpenSSL path'
   cd /home/vsts/work/_temp
   echo 'current directory'
   pwd
   ls
#- script: |
  # npm install -- global @salesforce/cli
  # echo 'sf cli installed'
