trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
    node --version
    sudo apt-get remove nodejs npm
    sudo apt-get update
    sudo apt-get upgrade
    curl -sL deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt-get install -y nodejs
    node -v
    npm -v
    npm install @salesforce/cli --global
