trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

#- task: UseNode@1
#  inputs:
#    checkLatest: true

- script:  |
   cd /usr/local/ssl
   ls 
   sudo find / -name usr/bin/openssl

#- script: |
  # npm install -- global @salesforce/cli
  # echo 'sf cli installed'
