steps:
- checkout: self
  fetchDepth: 0
- task: UseNode@1
  inputs:
    checkLatest: true

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

- script: |
   npm install -- global @salesforce/cli
   displayName: Install Salesforce CLI (new)
     
- task: DownloadSecureFile@1
  name: opensslCertificate
  displayName: 'Download OpenSSL Certificate
     inputs:
     secureFile: 'server.key'
