trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true


- task: UseNode@1
  inputs:
    version: '>=18.0.0'

- script: |
   npm install -- global @salesforce/cli
   echo 'sf cli installed'
