trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
    node --version
    sudo apt-get install nodejs
    sudo apt-get install npm
    nodejs --version
    sudo npm cache clean -f
    sudo npm install -g n
    npm install -g npm@latest
    npm install @salesforce/cli --global
