trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
    sudo apt install node
    node --version
    npm install @salesforce/cli -- global
    displayName: Install Salesforce CLI (new)
    npm install sfdx-cli — global
    sfdx --version

