trigger : none

pool:
  vmImage : ubuntu-20.04

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt-get install libssl-dev
      ls
      openssl version

#- task: UseNode@1
#  inputs:
#    checkLatest: true

- script:  |
   echo 'openssl-path'
   echo '0 current directory'
   cd /home/vsts/work/openssl
   ls
   cd /home/vsts/work
   ls

   cd /usr/bin/openssl
   ls
   echo '1current directory'
   pwd
   cd /usr/bin
   ls
   ls -l openssl
   
   chmod 775 /usr/bin/openssl
   ls

   
#- script: |
  # npm install -- global @salesforce/cli
  # echo 'sf cli installed'
