trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
    node --version
    sudo mkdir -p /usr/local/lib/nodejs
    sudo tar -xJvf node-v14.4.0-linux-x64.tar.xz -C /usr/local/lib/nodejs

    export PATH=/usr/local/lib/nodejs/node-node-v14.4.0-linux-x64/bin:$PATH
    npm install npm@latest -g
    node --version
    npm install -g npm@latest
    npm install @salesforce/cli --global
