trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
    node --version
    node -v
    nvm install v13.10.0
    nvm uninstall v9.2.0
    nvm install v9.2.0
    nvm uninstall v13.10.0
    npm install -g npm@latest
    npm install @salesforce/cli --global
