trigger : none

pool:
  vmImage : ubuntu-latest

steps:

- script: |
      sudo apt update
      apt show openssl
      sudo apt install openssl -y
      openssl version

- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
    sudo apt install node
    node --version
    npm install --save-dev @babel/plugin-proposal-class-properties
    npm cache clean --force
    npm uninstall -g react-native-cli
    npx create-react-app slaesforceADO
    npm cache verify
    npm install --global @salesforce/cli@latest-rc
    displayName: Install Salesforce CLI (new)
    npm install sfdx-cli — global
    sfdx --version

